import './globals.css';
import Sidebar from '@/components/sidebar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row w-[1000px] bg-zinc-100 mx-auto">
          <Sidebar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
